### ISSUE TITLE
Error executing process

### ISSUE THREAD

**Issue by znelson999** [ncbi/egapx#14] opened 2024-06-05 20:59 UTC
Hello Again,

I'm attempting to run EGAP on a new assembled genome and am getting a new error. Attached will be the code submitted via shell script and a portion of the slurm file output. This new genome is not hosted in NCBI, it is a local .fasta file that is roughly 5 times the size (2.1 gigabytes) of the other assembly I was working with in a previous issue. There is no transcriptome data included this time. 

Let me know if you need anything else from me.

[EgapxGSIAttempt1.txt](https://github.com/user-attachments/files/15596574/EgapxGSIAttempt1.txt)
[slurm-12686201.txt](https://github.com/user-attachments/files/15596557/slurm-12686201.txt)

**Comment by victzh** [comment] 2024-06-05 22:12
You seem to have a problem with incorrect docker/singularity image.
Can you look into /project/cricket_gen/ZachN/Virtual/WorkingDirectory/singularity, there should be a file ncbi_egapx.img.
If it's there, can you try
singularity shell /project/cricket_gen/ZachN/Virtual/WorkingDirectory/singularity/ncbi_egapx.img
You can try to rm -rf /project/cricket_gen/ZachN/Virtual/WorkingDirectory/singularity to clear the cached image.

Why when you run with -e singularity you get SLURM output file? You should use -e slurm and modify slurm.config file to tune it to your SLURM configuration and enable singularity in it.

After the first run there is a directory created for you by EGAPx - /project/cricket_gen/ZachN/egapx_config and there are several config files roughly corresponding to Nextflow 'executors'. If you run on SLURM using Singularity, you need to edit the file /project/cricket_gen/ZachN/egapx_config/slurm.config and replace /data/$USER with your network accessible space, probably /project/cricket_gen/ZachN. It will create extra 2 directories - tmp and singularity in it.
You may need to add some other parameters specific to your SLURM/Singularity installation. If you have publicly available documentation on your particular installation I can look into it.

**Comment by pstrope** [comment] 2024-06-14 20:12
Hi, 
It looks like egapx is using an older image from the cache. 
Did you try `rm -rf /project/cricket_gen/ZachN/Virtual/WorkingDirectory/singularity` to clear the cached image? Path to the `singularity`  dir could be different than this.

**Comment by pstrope** [comment] 2024-06-14 20:52
And make sure you have the latest scripts from github (v0.1.2-alpha).

**Comment by pstrope** [comment] 2024-06-17 17:20
What is the taxid you are using?

**Comment by znelson999** [comment] 2024-07-19 16:39
Hello, 

Sorry for the delay, our HPC went down for maintenance and another issue unrelated to EGAP popped up that was fixed last week. 

The taxid is 13551, this should correspond with Gryllus sigillatus which has been known as the banded house cricket. 

I have updated the script I was running with the updated code from github and deleted the cache, this has allowed the program to make it past the gnomon and chainer steps. However now its stopping at miniprot with an command exit status 137. Attached will be the tail end of the slurm out.

Any help is appreciated.
[slurmout2.txt](https://github.com/user-attachments/files/16314660/slurmout2.txt)

**Comment by pstrope** [comment] 2024-07-26 14:01
@znelson999 

A new version is out. We've made some updates to resource allocation, among others. Please try it and see if your error goes away. 

Pooja

**Comment by znelson999** [comment] 2024-08-06 17:33
@pstrope

Our HPC updated EGAP and I am still getting the same error. It seems the miniprot step is only being assigned 200gb of memory despite my requesting more for the job. Even placing the job in our large memory node and using 600gb it still throws the same out of memory error, confirmed by our HPC's technical support. Is there a way to have the script assign more memory for individual steps within the workflow?

Thanks

**Comment by pstrope** [comment] 2024-08-06 18:10
@znelson999 
You can edit the memory requirement by editing the `memory` for `huge_job` in this config file: 
`ui/assets/config/process_resources.config`

`miniprot` is assigned a `huge_job` in this file:
`nf/subworkflows/ncbi/target_proteins/miniprot/main.nf`

**Comment by pstrope** [comment] 2024-08-06 18:57
@znelson999 
How big is the genome you are running? And the size of the biggest sequence?

**Comment by znelson999** [comment] 2024-08-06 20:47
The fasta file itself is 2.1gb while the largest scaffold is about 417 megabases, several scaffolds are larger than 100 megabases. Was this what you were asking for?

**Comment by pstrope** [comment] 2024-08-06 21:48
yes, thank you.

**Comment by pstrope** [comment] 2024-08-09 00:58
Hi @znelson999 
We've made small changes to how protein set is made at our end. This has allowed tests on large genomes to run the miniprot step under 200gb memory. Your run should automatically pick the new protein set. If you are were running using the offline mode, then you will have to re-run the download data part first. Please let us know how it goes.

Pooja

**Comment by znelson999** [comment] 2024-08-09 16:38
Hello @pstrope 
The run was successful after adjusting the amount of memory allowed in the config file. Thank you for all of your help. 
You might see me again at some point as you continue to update.

**Comment by victzh** [comment] 2024-08-22 21:35
As the problem is resolved, I'm closing this ticket.

**Closed by victzh** 2024-08-22 21:35 UTC
