### ISSUE TITLE
offline mode?

### ISSUE THREAD

**Issue by OH-AU** [ncbi/egapx#11] opened 2024-05-13 03:09 UTC
Although I can download most files in advance, it appears that some downloads are hardcoded into the source?
Specifically:
```
./ui/egapx.py:    taxids_file = urlopen("
[https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/EGAP/target_proteins/taxid.list")](https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/EGAP/target_proteins/taxid.list%22))
./ui/egapx.py:    return f'
[https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/EGAP/target_proteins/{best_taxid}.faa.gz'](https://ftp.ncbi.nlm.nih.gov/genomes/TOOLS/EGAP/target_proteins/%7Bbest_taxid%7D.faa.gz%27)
```
Would it be possible to set it up so that downloads could be run independently in advance and a local directory check to see if the files exist before attempting a download as running on a HPC system, the compute nodes themselves are firewalled.
Thanks.

**Comment by Andy-B-123** [comment] 2024-05-13 03:48
Hi, just chiming in that I would love this support as well! Our HPC environment is similarly locked down for internet access for compute nodes.

**Comment by pstrope** [comment] 2024-05-13 12:27
Hi, 

Thank you for bringing up this issue. We will consider this in our planning for future updates. We will reach out once we have developed the offline mode. 

Pooja

**Comment by victzh** [comment] 2024-05-13 15:02
In case of compute nodes firewalled from the Internet you can't use HTTP(S) URLs as a data source as well, and you can't use SRA accessions and SRA queries for reads. If that's OK, we can move all the data download to the main node before starting the cluster execution. If the main node is also isolated it makes more problems for us to work around.

**Comment by OH-AU** [comment] 2024-05-14 00:41
The above would work for our institute. Many often have a node specifically for the purposes of moving/downloading data, but that node shouldn't be used for any compute. Running a multi-step process would work for me as well e.g. 1) data prep/download 2) analysis etc.

**Comment by Andy-B-123** [comment] 2024-05-14 01:05
Yes, I'd be totally happy running a two-step process!

Generally I would be having read files locally and would be happy running something which would check and update databases as an initial step, and then running the compute heavy workflow afterwards.

Thank you for considering this, it's a block at the moment for implementing this in my workflow too!

**Comment by pstrope** [comment] 2024-07-26 13:57
Hi @Andy-B-123, @OH-AU 
A new version is out. It has off-line mode. Please try it out!

Pooja

**Comment by Andy-B-123** [comment] 2024-07-30 06:15
Hi @pstrope, thank you so much for supporting this in the latest release! Really appreciate the time and work involved, I am sure it will be helpful for many users like myself wanting to stage things. 

Can confirm that the offline mode works with the example data provided for the basic 'input\_D\_farinae\_small.yaml' and protein dataset when I had the reads and genome downloaded locally. Will try the remaining workflows as I go but this is a pretty great sign for us!   
  
Thank you and the team for your diligence on this. It ran without error from the start - an absolute standout for me for a bioinformatic pipeline program which has to work on so many systems!

**Comment by victzh** [comment] 2024-08-22 23:27
The issue is resolved, I'm closing this ticket.

**Closed by victzh** 2024-08-22 23:27 UTC
